# Visualization setting
/control/execute init_vis.mac

# Initialize kernel
/jpetmc/detector/loadOnlyScintillators
/jpetmc/detector/loadModularLayer Single
#/jpetmc/detector/loadModularLayer Double
#/jpetmc/detector/loadJPetBasicGeom 

/jpetmc/source/setType isotope 

#/jpetmc/source/isotope/setShape cylinder
/jpetmc/source/isotope/setNGamma 1 
/jpetmc/source/isotope/setShape/cylinderRadius 0
/jpetmc/source/isotope/setShape/cylinderZ 0


/run/initialize


#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.

/run/beamOn 10000
