# Macro setting barrel and modular detector (24 part ring)
# Using small annihilation chamber

/jpetmc/detector/loadTargetForRun 5

# Loading standard scintillators (3 layers with frame)
/jpetmc/detector/loadJPetBasicGeom

# Loading modular layers
/jpetmc/detector/loadModularLayer Single
# Do not load three layers of standard detector
#/jpetmc/detector/loadModularLayerOnly

# Loading scintillators without frame
/jpetmc/detector/loadOnlyScintillators

# Creating geometry file for analysis of the Framework
/jpetmc/detector/createGeometryType barrel
/jpetmc/detector/geometryFileName modular_mc_setup.json

/run/initialize

/run/beamOn 100000
