#include "SteppingAction.h"
#include "G4TransportationManager.hh" 
#include "G4SteppingManager.hh"
#include "PrimaryParticleInformation.h"
#include "G4PrimaryParticle.hh"


SteppingAction::SteppingAction()
{
     G4TransportationManager::GetTransportationManager()->GetNavigatorForTracking()->SetPushVerbosity(0);
}


SteppingAction::~SteppingAction()
{}

void SteppingAction::UserSteppingAction(const G4Step* aStep)
{
  // execute code for
  // - generated by user gamma quanta
  // - physical effects that does not occur in Sensitive Detector
  if("Transportation"==aStep->GetPostStepPoint()->GetProcessDefinedStep()->GetProcessName()) return;
  if(aStep->GetTrack()->GetParentID() != 0 ) return;
  if(nullptr != aStep->GetPostStepPoint()->GetPhysicalVolume()->GetLogicalVolume()->GetSensitiveDetector() ) return;

  PrimaryParticleInformation* info  = static_cast<PrimaryParticleInformation*> (aStep->GetTrack()->GetDynamicParticle()->GetPrimaryParticle()->GetUserInformation());
  if (info != 0 ){
    // particle quanta interact in phantom or frame (but not SD!)
    info->SetGammaMultiplicity(0);
  }
}
